import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { ToastContainer } from "react-toastify";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



const publishableKey="pk_test_ZGVmaW5pdGUtbmFyd2hhbC02MS5jbGVyay5hY2NvdW50cy5kZXYk";
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider publishableKey={publishableKey}>
    <html lang="en">
      
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased` }
      >
      
        {children}
        <ToastContainer />
      </body>
    </html>
    </ClerkProvider>
  );
}
